# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2017-07-03 17:36
from __future__ import unicode_literals

from django.db import migrations, models
import pugorugh.models


class Migration(migrations.Migration):

    dependencies = [
        ('pugorugh', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dog',
            name='image_filename',
            field=models.ImageField(blank=True, null=True, upload_to=pugorugh.models.image_folder),
        ),
    ]
